const wsudgrs = [
  {
    "FISCAL_YEAR":2007,
    "CAMPUS":"Pullman",
    "Level":"Bachelors",
    "AWARDS":3515
  },
  {
    "FISCAL_YEAR":2008,
    "CAMPUS":"Pullman",
    "Level":"Bachelors",
    "AWARDS":3481
  },
  {
    "FISCAL_YEAR":2009,
    "CAMPUS":"Pullman",
    "Level":"Bachelors",
    "AWARDS":3409
  },
  {
    "FISCAL_YEAR":2010,
    "CAMPUS":"Pullman",
    "Level":"Bachelors",
    "AWARDS":3265
  },
  {
    "FISCAL_YEAR":2011,
    "CAMPUS":"Pullman",
    "Level":"Bachelors",
    "AWARDS":3441
  },
  {
    "FISCAL_YEAR":2012,
    "CAMPUS":"Pullman",
    "Level":"Bachelors",
    "AWARDS":3502
  },
  {
    "FISCAL_YEAR":2013,
    "CAMPUS":"Pullman",
    "Level":"Bachelors",
    "AWARDS":3460
  },
  {
    "FISCAL_YEAR":2014,
    "CAMPUS":"Pullman",
    "Level":"Bachelors",
    "AWARDS":3205
  },
  {
    "FISCAL_YEAR":2015,
    "CAMPUS":"Pullman",
    "Level":"Bachelors",
    "AWARDS":3555
  },
  {
    "FISCAL_YEAR":2016,
    "CAMPUS":"Pullman",
    "Level":"Bachelors",
    "AWARDS":3456
  },
  {
    "FISCAL_YEAR":2017,
    "CAMPUS":"Pullman",
    "Level":"Bachelors",
    "AWARDS":3406
  },
  {
    "FISCAL_YEAR":2007,
    "CAMPUS":"Pullman",
    "Level":"Professional",
    "AWARDS":219
  },
  {
    "FISCAL_YEAR":2008,
    "CAMPUS":"Pullman",
    "Level":"Professional",
    "AWARDS":186
  },
  {
    "FISCAL_YEAR":2009,
    "CAMPUS":"Pullman",
    "Level":"Professional",
    "AWARDS":180
  },
  {
    "FISCAL_YEAR":2010,
    "CAMPUS":"Pullman",
    "Level":"Professional",
    "AWARDS":181
  },
  {
    "FISCAL_YEAR":2011,
    "CAMPUS":"Pullman",
    "Level":"Professional",
    "AWARDS":116
  },
  {
    "FISCAL_YEAR":2012,
    "CAMPUS":"Pullman",
    "Level":"Professional",
    "AWARDS":99
  },
  {
    "FISCAL_YEAR":2013,
    "CAMPUS":"Pullman",
    "Level":"Professional",
    "AWARDS":94
  },
  {
    "FISCAL_YEAR":2014,
    "CAMPUS":"Pullman",
    "Level":"Professional",
    "AWARDS":97
  },
  {
    "FISCAL_YEAR":2015,
    "CAMPUS":"Pullman",
    "Level":"Professional",
    "AWARDS":98
  },
  {
    "FISCAL_YEAR":2016,
    "CAMPUS":"Pullman",
    "Level":"Professional",
    "AWARDS":124
  },
  {
    "FISCAL_YEAR":2017,
    "CAMPUS":"Pullman",
    "Level":"Professional",
    "AWARDS":122
  },
  {
    "FISCAL_YEAR":2007,
    "CAMPUS":"Pullman",
    "Level":"Masters",
    "AWARDS":453
  },
  {
    "FISCAL_YEAR":2008,
    "CAMPUS":"Pullman",
    "Level":"Masters",
    "AWARDS":416
  },
  {
    "FISCAL_YEAR":2009,
    "CAMPUS":"Pullman",
    "Level":"Masters",
    "AWARDS":426
  },
  {
    "FISCAL_YEAR":2010,
    "CAMPUS":"Pullman",
    "Level":"Masters",
    "AWARDS":443
  },
  {
    "FISCAL_YEAR":2011,
    "CAMPUS":"Pullman",
    "Level":"Masters",
    "AWARDS":440
  },
  {
    "FISCAL_YEAR":2012,
    "CAMPUS":"Pullman",
    "Level":"Masters",
    "AWARDS":442
  },
  {
    "FISCAL_YEAR":2013,
    "CAMPUS":"Pullman",
    "Level":"Masters",
    "AWARDS":398
  },
  {
    "FISCAL_YEAR":2014,
    "CAMPUS":"Pullman",
    "Level":"Masters",
    "AWARDS":352
  },
  {
    "FISCAL_YEAR":2015,
    "CAMPUS":"Pullman",
    "Level":"Masters",
    "AWARDS":353
  },
  {
    "FISCAL_YEAR":2016,
    "CAMPUS":"Pullman",
    "Level":"Masters",
    "AWARDS":392
  },
  {
    "FISCAL_YEAR":2017,
    "CAMPUS":"Pullman",
    "Level":"Masters",
    "AWARDS":382
  },
  {
    "FISCAL_YEAR":2007,
    "CAMPUS":"Pullman",
    "Level":"Doctoral",
    "AWARDS":175
  },
  {
    "FISCAL_YEAR":2008,
    "CAMPUS":"Pullman",
    "Level":"Doctoral",
    "AWARDS":183
  },
  {
    "FISCAL_YEAR":2009,
    "CAMPUS":"Pullman",
    "Level":"Doctoral",
    "AWARDS":190
  },
  {
    "FISCAL_YEAR":2010,
    "CAMPUS":"Pullman",
    "Level":"Doctoral",
    "AWARDS":184
  },
  {
    "FISCAL_YEAR":2011,
    "CAMPUS":"Pullman",
    "Level":"Doctoral",
    "AWARDS":204
  },
  {
    "FISCAL_YEAR":2012,
    "CAMPUS":"Pullman",
    "Level":"Doctoral",
    "AWARDS":193
  },
  {
    "FISCAL_YEAR":2013,
    "CAMPUS":"Pullman",
    "Level":"Doctoral",
    "AWARDS":247
  },
  {
    "FISCAL_YEAR":2014,
    "CAMPUS":"Pullman",
    "Level":"Doctoral",
    "AWARDS":234
  },
  {
    "FISCAL_YEAR":2015,
    "CAMPUS":"Pullman",
    "Level":"Doctoral",
    "AWARDS":244
  },
  {
    "FISCAL_YEAR":2016,
    "CAMPUS":"Pullman",
    "Level":"Doctoral",
    "AWARDS":252
  },
  {
    "FISCAL_YEAR":2017,
    "CAMPUS":"Pullman",
    "Level":"Doctoral",
    "AWARDS":252
  },
  {
    "FISCAL_YEAR":2007,
    "CAMPUS":"Spokane",
    "Level":"Bachelors",
    "AWARDS":319
  },
  {
    "FISCAL_YEAR":2008,
    "CAMPUS":"Spokane",
    "Level":"Bachelors",
    "AWARDS":331
  },
  {
    "FISCAL_YEAR":2009,
    "CAMPUS":"Spokane",
    "Level":"Bachelors",
    "AWARDS":350
  },
  {
    "FISCAL_YEAR":2010,
    "CAMPUS":"Spokane",
    "Level":"Bachelors",
    "AWARDS":269
  },
  {
    "FISCAL_YEAR":2011,
    "CAMPUS":"Spokane",
    "Level":"Bachelors",
    "AWARDS":341
  },
  {
    "FISCAL_YEAR":2012,
    "CAMPUS":"Spokane",
    "Level":"Bachelors",
    "AWARDS":327
  },
  {
    "FISCAL_YEAR":2013,
    "CAMPUS":"Spokane",
    "Level":"Bachelors",
    "AWARDS":304
  },
  {
    "FISCAL_YEAR":2014,
    "CAMPUS":"Spokane",
    "Level":"Bachelors",
    "AWARDS":306
  },
  {
    "FISCAL_YEAR":2015,
    "CAMPUS":"Spokane",
    "Level":"Bachelors",
    "AWARDS":284
  },
  {
    "FISCAL_YEAR":2016,
    "CAMPUS":"Spokane",
    "Level":"Bachelors",
    "AWARDS":307
  },
  {
    "FISCAL_YEAR":2017,
    "CAMPUS":"Spokane",
    "Level":"Bachelors",
    "AWARDS":289
  },
  {
    "FISCAL_YEAR":2007,
    "CAMPUS":"Spokane",
    "Level":"Professional",
    "AWARDS":0
  },
  {
    "FISCAL_YEAR":2008,
    "CAMPUS":"Spokane",
    "Level":"Professional",
    "AWARDS":2
  },
  {
    "FISCAL_YEAR":2009,
    "CAMPUS":"Spokane",
    "Level":"Professional",
    "AWARDS":11
  },
  {
    "FISCAL_YEAR":2010,
    "CAMPUS":"Spokane",
    "Level":"Professional",
    "AWARDS":7
  },
  {
    "FISCAL_YEAR":2011,
    "CAMPUS":"Spokane",
    "Level":"Professional",
    "AWARDS":80
  },
  {
    "FISCAL_YEAR":2012,
    "CAMPUS":"Spokane",
    "Level":"Professional",
    "AWARDS":78
  },
  {
    "FISCAL_YEAR":2013,
    "CAMPUS":"Spokane",
    "Level":"Professional",
    "AWARDS":95
  },
  {
    "FISCAL_YEAR":2014,
    "CAMPUS":"Spokane",
    "Level":"Professional",
    "AWARDS":81
  },
  {
    "FISCAL_YEAR":2015,
    "CAMPUS":"Spokane",
    "Level":"Professional",
    "AWARDS":85
  },
  {
    "FISCAL_YEAR":2016,
    "CAMPUS":"Spokane",
    "Level":"Professional",
    "AWARDS":114
  },
  {
    "FISCAL_YEAR":2017,
    "CAMPUS":"Spokane",
    "Level":"Professional",
    "AWARDS":94
  },
  {
    "FISCAL_YEAR":2007,
    "CAMPUS":"Spokane",
    "Level":"Masters",
    "AWARDS":55
  },
  {
    "FISCAL_YEAR":2008,
    "CAMPUS":"Spokane",
    "Level":"Masters",
    "AWARDS":82
  },
  {
    "FISCAL_YEAR":2009,
    "CAMPUS":"Spokane",
    "Level":"Masters",
    "AWARDS":76
  },
  {
    "FISCAL_YEAR":2010,
    "CAMPUS":"Spokane",
    "Level":"Masters",
    "AWARDS":78
  },
  {
    "FISCAL_YEAR":2011,
    "CAMPUS":"Spokane",
    "Level":"Masters",
    "AWARDS":82
  },
  {
    "FISCAL_YEAR":2012,
    "CAMPUS":"Spokane",
    "Level":"Masters",
    "AWARDS":93
  },
  {
    "FISCAL_YEAR":2013,
    "CAMPUS":"Spokane",
    "Level":"Masters",
    "AWARDS":90
  },
  {
    "FISCAL_YEAR":2014,
    "CAMPUS":"Spokane",
    "Level":"Masters",
    "AWARDS":92
  },
  {
    "FISCAL_YEAR":2015,
    "CAMPUS":"Spokane",
    "Level":"Masters",
    "AWARDS":68
  },
  {
    "FISCAL_YEAR":2016,
    "CAMPUS":"Spokane",
    "Level":"Masters",
    "AWARDS":89
  },
  {
    "FISCAL_YEAR":2017,
    "CAMPUS":"Spokane",
    "Level":"Masters",
    "AWARDS":104
  },
  {
    "FISCAL_YEAR":2007,
    "CAMPUS":"Spokane",
    "Level":"Doctoral",
    "AWARDS":0
  },
  {
    "FISCAL_YEAR":2008,
    "CAMPUS":"Spokane",
    "Level":"Doctoral",
    "AWARDS":0
  },
  {
    "FISCAL_YEAR":2009,
    "CAMPUS":"Spokane",
    "Level":"Doctoral",
    "AWARDS":1
  },
  {
    "FISCAL_YEAR":2010,
    "CAMPUS":"Spokane",
    "Level":"Doctoral",
    "AWARDS":0
  },
  {
    "FISCAL_YEAR":2011,
    "CAMPUS":"Spokane",
    "Level":"Doctoral",
    "AWARDS":3
  },
  {
    "FISCAL_YEAR":2012,
    "CAMPUS":"Spokane",
    "Level":"Doctoral",
    "AWARDS":6
  },
  {
    "FISCAL_YEAR":2013,
    "CAMPUS":"Spokane",
    "Level":"Doctoral",
    "AWARDS":12
  },
  {
    "FISCAL_YEAR":2014,
    "CAMPUS":"Spokane",
    "Level":"Doctoral",
    "AWARDS":10
  },
  {
    "FISCAL_YEAR":2015,
    "CAMPUS":"Spokane",
    "Level":"Doctoral",
    "AWARDS":23
  },
  {
    "FISCAL_YEAR":2016,
    "CAMPUS":"Spokane",
    "Level":"Doctoral",
    "AWARDS":29
  },
  {
    "FISCAL_YEAR":2017,
    "CAMPUS":"Spokane",
    "Level":"Doctoral",
    "AWARDS":26
  },
  {
    "FISCAL_YEAR":2007,
    "CAMPUS":"Tri-Cities",
    "Level":"Bachelors",
    "AWARDS":212
  },
  {
    "FISCAL_YEAR":2008,
    "CAMPUS":"Tri-Cities",
    "Level":"Bachelors",
    "AWARDS":188
  },
  {
    "FISCAL_YEAR":2009,
    "CAMPUS":"Tri-Cities",
    "Level":"Bachelors",
    "AWARDS":262
  },
  {
    "FISCAL_YEAR":2010,
    "CAMPUS":"Tri-Cities",
    "Level":"Bachelors",
    "AWARDS":283
  },
  {
    "FISCAL_YEAR":2011,
    "CAMPUS":"Tri-Cities",
    "Level":"Bachelors",
    "AWARDS":316
  },
  {
    "FISCAL_YEAR":2012,
    "CAMPUS":"Tri-Cities",
    "Level":"Bachelors",
    "AWARDS":301
  },
  {
    "FISCAL_YEAR":2013,
    "CAMPUS":"Tri-Cities",
    "Level":"Bachelors",
    "AWARDS":283
  },
  {
    "FISCAL_YEAR":2014,
    "CAMPUS":"Tri-Cities",
    "Level":"Bachelors",
    "AWARDS":287
  },
  {
    "FISCAL_YEAR":2015,
    "CAMPUS":"Tri-Cities",
    "Level":"Bachelors",
    "AWARDS":277
  },
  {
    "FISCAL_YEAR":2016,
    "CAMPUS":"Tri-Cities",
    "Level":"Bachelors",
    "AWARDS":308
  },
  {
    "FISCAL_YEAR":2017,
    "CAMPUS":"Tri-Cities",
    "Level":"Bachelors",
    "AWARDS":292
  },
  {
    "FISCAL_YEAR":2007,
    "CAMPUS":"Tri-Cities",
    "Level":"Masters",
    "AWARDS":68
  },
  {
    "FISCAL_YEAR":2008,
    "CAMPUS":"Tri-Cities",
    "Level":"Masters",
    "AWARDS":79
  },
  {
    "FISCAL_YEAR":2009,
    "CAMPUS":"Tri-Cities",
    "Level":"Masters",
    "AWARDS":71
  },
  {
    "FISCAL_YEAR":2010,
    "CAMPUS":"Tri-Cities",
    "Level":"Masters",
    "AWARDS":77
  },
  {
    "FISCAL_YEAR":2011,
    "CAMPUS":"Tri-Cities",
    "Level":"Masters",
    "AWARDS":71
  },
  {
    "FISCAL_YEAR":2012,
    "CAMPUS":"Tri-Cities",
    "Level":"Masters",
    "AWARDS":88
  },
  {
    "FISCAL_YEAR":2013,
    "CAMPUS":"Tri-Cities",
    "Level":"Masters",
    "AWARDS":87
  },
  {
    "FISCAL_YEAR":2014,
    "CAMPUS":"Tri-Cities",
    "Level":"Masters",
    "AWARDS":50
  },
  {
    "FISCAL_YEAR":2015,
    "CAMPUS":"Tri-Cities",
    "Level":"Masters",
    "AWARDS":51
  },
  {
    "FISCAL_YEAR":2016,
    "CAMPUS":"Tri-Cities",
    "Level":"Masters",
    "AWARDS":38
  },
  {
    "FISCAL_YEAR":2017,
    "CAMPUS":"Tri-Cities",
    "Level":"Masters",
    "AWARDS":43
  },
  {
    "FISCAL_YEAR":2007,
    "CAMPUS":"Tri-Cities",
    "Level":"Doctoral",
    "AWARDS":0
  },
  {
    "FISCAL_YEAR":2008,
    "CAMPUS":"Tri-Cities",
    "Level":"Doctoral",
    "AWARDS":1
  },
  {
    "FISCAL_YEAR":2009,
    "CAMPUS":"Tri-Cities",
    "Level":"Doctoral",
    "AWARDS":0
  },
  {
    "FISCAL_YEAR":2010,
    "CAMPUS":"Tri-Cities",
    "Level":"Doctoral",
    "AWARDS":0
  },
  {
    "FISCAL_YEAR":2011,
    "CAMPUS":"Tri-Cities",
    "Level":"Doctoral",
    "AWARDS":0
  },
  {
    "FISCAL_YEAR":2012,
    "CAMPUS":"Tri-Cities",
    "Level":"Doctoral",
    "AWARDS":0
  },
  {
    "FISCAL_YEAR":2013,
    "CAMPUS":"Tri-Cities",
    "Level":"Doctoral",
    "AWARDS":4
  },
  {
    "FISCAL_YEAR":2014,
    "CAMPUS":"Tri-Cities",
    "Level":"Doctoral",
    "AWARDS":11
  },
  {
    "FISCAL_YEAR":2015,
    "CAMPUS":"Tri-Cities",
    "Level":"Doctoral",
    "AWARDS":10
  },
  {
    "FISCAL_YEAR":2016,
    "CAMPUS":"Tri-Cities",
    "Level":"Doctoral",
    "AWARDS":11
  },
  {
    "FISCAL_YEAR":2017,
    "CAMPUS":"Tri-Cities",
    "Level":"Doctoral",
    "AWARDS":10
  },
  {
    "FISCAL_YEAR":2007,
    "CAMPUS":"Vancouver",
    "Level":"Bachelors",
    "AWARDS":513
  },
  {
    "FISCAL_YEAR":2008,
    "CAMPUS":"Vancouver",
    "Level":"Bachelors",
    "AWARDS":529
  },
  {
    "FISCAL_YEAR":2009,
    "CAMPUS":"Vancouver",
    "Level":"Bachelors",
    "AWARDS":605
  },
  {
    "FISCAL_YEAR":2010,
    "CAMPUS":"Vancouver",
    "Level":"Bachelors",
    "AWARDS":616
  },
  {
    "FISCAL_YEAR":2011,
    "CAMPUS":"Vancouver",
    "Level":"Bachelors",
    "AWARDS":683
  },
  {
    "FISCAL_YEAR":2012,
    "CAMPUS":"Vancouver",
    "Level":"Bachelors",
    "AWARDS":776
  },
  {
    "FISCAL_YEAR":2013,
    "CAMPUS":"Vancouver",
    "Level":"Bachelors",
    "AWARDS":752
  },
  {
    "FISCAL_YEAR":2014,
    "CAMPUS":"Vancouver",
    "Level":"Bachelors",
    "AWARDS":733
  },
  {
    "FISCAL_YEAR":2015,
    "CAMPUS":"Vancouver",
    "Level":"Bachelors",
    "AWARDS":788
  },
  {
    "FISCAL_YEAR":2016,
    "CAMPUS":"Vancouver",
    "Level":"Bachelors",
    "AWARDS":782
  },
  {
    "FISCAL_YEAR":2017,
    "CAMPUS":"Vancouver",
    "Level":"Bachelors",
    "AWARDS":851
  },
  {
    "FISCAL_YEAR":2007,
    "CAMPUS":"Vancouver",
    "Level":"Masters",
    "AWARDS":119
  },
  {
    "FISCAL_YEAR":2008,
    "CAMPUS":"Vancouver",
    "Level":"Masters",
    "AWARDS":137
  },
  {
    "FISCAL_YEAR":2009,
    "CAMPUS":"Vancouver",
    "Level":"Masters",
    "AWARDS":116
  },
  {
    "FISCAL_YEAR":2010,
    "CAMPUS":"Vancouver",
    "Level":"Masters",
    "AWARDS":131
  },
  {
    "FISCAL_YEAR":2011,
    "CAMPUS":"Vancouver",
    "Level":"Masters",
    "AWARDS":141
  },
  {
    "FISCAL_YEAR":2012,
    "CAMPUS":"Vancouver",
    "Level":"Masters",
    "AWARDS":140
  },
  {
    "FISCAL_YEAR":2013,
    "CAMPUS":"Vancouver",
    "Level":"Masters",
    "AWARDS":142
  },
  {
    "FISCAL_YEAR":2014,
    "CAMPUS":"Vancouver",
    "Level":"Masters",
    "AWARDS":143
  },
  {
    "FISCAL_YEAR":2015,
    "CAMPUS":"Vancouver",
    "Level":"Masters",
    "AWARDS":94
  },
  {
    "FISCAL_YEAR":2016,
    "CAMPUS":"Vancouver",
    "Level":"Masters",
    "AWARDS":115
  },
  {
    "FISCAL_YEAR":2017,
    "CAMPUS":"Vancouver",
    "Level":"Masters",
    "AWARDS":105
  },
  {
    "FISCAL_YEAR":2007,
    "CAMPUS":"Vancouver",
    "Level":"Doctoral",
    "AWARDS":0
  },
  {
    "FISCAL_YEAR":2008,
    "CAMPUS":"Vancouver",
    "Level":"Doctoral",
    "AWARDS":5
  },
  {
    "FISCAL_YEAR":2009,
    "CAMPUS":"Vancouver",
    "Level":"Doctoral",
    "AWARDS":4
  },
  {
    "FISCAL_YEAR":2010,
    "CAMPUS":"Vancouver",
    "Level":"Doctoral",
    "AWARDS":1
  },
  {
    "FISCAL_YEAR":2011,
    "CAMPUS":"Vancouver",
    "Level":"Doctoral",
    "AWARDS":4
  },
  {
    "FISCAL_YEAR":2012,
    "CAMPUS":"Vancouver",
    "Level":"Doctoral",
    "AWARDS":4
  },
  {
    "FISCAL_YEAR":2013,
    "CAMPUS":"Vancouver",
    "Level":"Doctoral",
    "AWARDS":5
  },
  {
    "FISCAL_YEAR":2014,
    "CAMPUS":"Vancouver",
    "Level":"Doctoral",
    "AWARDS":5
  },
  {
    "FISCAL_YEAR":2015,
    "CAMPUS":"Vancouver",
    "Level":"Doctoral",
    "AWARDS":13
  },
  {
    "FISCAL_YEAR":2016,
    "CAMPUS":"Vancouver",
    "Level":"Doctoral",
    "AWARDS":30
  },
  {
    "FISCAL_YEAR":2017,
    "CAMPUS":"Vancouver",
    "Level":"Doctoral",
    "AWARDS":27
  },
  {
    "FISCAL_YEAR":2007,
    "CAMPUS":"WSU Online",
    "Level":"Bachelors",
    "AWARDS":239
  },
  {
    "FISCAL_YEAR":2008,
    "CAMPUS":"WSU Online",
    "Level":"Bachelors",
    "AWARDS":289
  },
  {
    "FISCAL_YEAR":2009,
    "CAMPUS":"WSU Online",
    "Level":"Bachelors",
    "AWARDS":281
  },
  {
    "FISCAL_YEAR":2010,
    "CAMPUS":"WSU Online",
    "Level":"Bachelors",
    "AWARDS":346
  },
  {
    "FISCAL_YEAR":2011,
    "CAMPUS":"WSU Online",
    "Level":"Bachelors",
    "AWARDS":440
  },
  {
    "FISCAL_YEAR":2012,
    "CAMPUS":"WSU Online",
    "Level":"Bachelors",
    "AWARDS":391
  },
  {
    "FISCAL_YEAR":2013,
    "CAMPUS":"WSU Online",
    "Level":"Bachelors",
    "AWARDS":476
  },
  {
    "FISCAL_YEAR":2014,
    "CAMPUS":"WSU Online",
    "Level":"Bachelors",
    "AWARDS":523
  },
  {
    "FISCAL_YEAR":2015,
    "CAMPUS":"WSU Online",
    "Level":"Bachelors",
    "AWARDS":609
  },
  {
    "FISCAL_YEAR":2016,
    "CAMPUS":"WSU Online",
    "Level":"Bachelors",
    "AWARDS":591
  },
  {
    "FISCAL_YEAR":2017,
    "CAMPUS":"WSU Online",
    "Level":"Bachelors",
    "AWARDS":684
  },
  {
    "FISCAL_YEAR":2007,
    "CAMPUS":"WSU Online",
    "Level":"Masters",
    "AWARDS":7
  },
  {
    "FISCAL_YEAR":2008,
    "CAMPUS":"WSU Online",
    "Level":"Masters",
    "AWARDS":10
  },
  {
    "FISCAL_YEAR":2009,
    "CAMPUS":"WSU Online",
    "Level":"Masters",
    "AWARDS":22
  },
  {
    "FISCAL_YEAR":2010,
    "CAMPUS":"WSU Online",
    "Level":"Masters",
    "AWARDS":19
  },
  {
    "FISCAL_YEAR":2011,
    "CAMPUS":"WSU Online",
    "Level":"Masters",
    "AWARDS":29
  },
  {
    "FISCAL_YEAR":2012,
    "CAMPUS":"WSU Online",
    "Level":"Masters",
    "AWARDS":39
  },
  {
    "FISCAL_YEAR":2013,
    "CAMPUS":"WSU Online",
    "Level":"Masters",
    "AWARDS":83
  },
  {
    "FISCAL_YEAR":2014,
    "CAMPUS":"WSU Online",
    "Level":"Masters",
    "AWARDS":94
  },
  {
    "FISCAL_YEAR":2015,
    "CAMPUS":"WSU Online",
    "Level":"Masters",
    "AWARDS":175
  },
  {
    "FISCAL_YEAR":2016,
    "CAMPUS":"WSU Online",
    "Level":"Masters",
    "AWARDS":258
  },
  {
    "FISCAL_YEAR":2017,
    "CAMPUS":"WSU Online",
    "Level":"Masters",
    "AWARDS":326
  },
  {
    "FISCAL_YEAR":2016,
    "CAMPUS":"Everrett",
    "Level":"Bachelors",
    "AWARDS":31
  },
  {
    "FISCAL_YEAR":2017,
    "CAMPUS":"Everrett",
    "Level":"Bachelors",
    "AWARDS":75
  }
];